version: "3.4"

networks:
  app-tier:
    driver: bridge

services:
  nginx:
    image: "bitnami/nginx:latest"
    ports:
      - "80:8080"
    volumes:
      - ./Docker/nginx/vhosts/my_server_block_http_https.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block_http_https.conf:ro
    depends_on:
      - php-fpm
    networks:
      - app-tier

  php-fpm:
    tty: true
    image: "bitnami/php-fpm:latest"
    volumes:
      - .:/app
    networks:
      - app-tier
