<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBxWTMJb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBxWTMJb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBxWTMJb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBxWTMJb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBxWTMJb\App_KernelDevDebugContainer([
    'container.build_hash' => 'BxWTMJb',
    'container.build_id' => 'f5f629e1',
    'container.build_time' => 1600072247,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBxWTMJb');
